{% set name = "iso4217" %}
{% set version = "1.9.20220401" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4c954a0c42e42a064cc226781cde39f88fe056959a391e2367c5e544d3107d2

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - iso4217
    - iso4217.test

about:
  home: https://github.com/dahlia/iso4217
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  summary: ISO 4217 currency data package for Python

  doc_url: ''
  dev_url: https://github.com/dahlia/iso4217

extra:
  recipe-maintainers:
    - gerrymanoim
    - jbredeche
    - jdricklefs
    - llllllllll
    - richafrank
